
services:
  postgres:  # Base de données principale (Développement / Production)
    image: postgres:14
    container_name: post_it_db
    environment:
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DEV_POSTGRES_USER}"]
      interval: 10s
      retries: 5

  test_postgres:  # Base de données dédiée aux tests
    image: postgres:14
    container_name: post_it_test_db
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    volumes:
      - db_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # ⚠ Attention, PostgreSQL tourne sur 5432 dans le conteneur mais est mappé sur 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_POSTGRES_USER}"]
      interval: 10s
      retries: 5

  flask_app:  # Service Flask
    build: .
    container_name: flask_app
    env_file: 
      - .env
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      test_postgres:
        condition: service_healthy
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DEV_DATABASE_URL: ${DEV_DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
    entrypoint: >
      sh -c "if [ \"$FLASK_ENV\" = \"testing\" ]; then
      until pg_isready -h test_postgres -p 5432; do sleep 5; done;
      export DATABASE_URL=$TEST_DATABASE_URL;
      else
      until pg_isready -h postgres -p 5432; do sleep 5; done;
      fi;
      python run.py"

volumes:
  db_data:
  db_test_data:
