"""Initialisation bdd

Revision ID: 010337919d7d
Revises: 
Create Date: 2025-04-01 14:24:41.205056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010337919d7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('postits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=25), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postits')
    op.drop_table('users')
    # ### end Alembic commands ###
