"""Aubaisser aractères titres à 25

Revision ID: d5e1270b2216
Revises: 0c63ac971705
Create Date: 2025-03-04 18:01:57.004408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e1270b2216'
down_revision = '0c63ac971705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postits', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postits', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
